### ISSUE TITLE
WebRequest is missing setRequestParameters method

### ISSUE THREAD

**Issue by imachabeli** [HtmlUnit/NHtmlUnit#15]
So I tried to call WebRequest.WObj.setRequestParameters but can't figure out what to pass as arguments since com.gargoylesoftware.htmlunit.WebRequest is expecting java.Util.List

**Comment by asbjornu** [comment]
If you use the `WObj`-properties, you're in Java land and need to use the Java types as they are exposed through [IKVM](http://www.ikvm.net/).
