### ISSUE TITLE
AlertHandler  in NhtmlUnit

### ISSUE THREAD

**Issue by samuelnyamukapa** [HtmlUnit/NHtmlUnit#17]
I am trying to use the AlertHandler as follows:
 
            java.util.List collectedAlerts = new ArrayList();
            webClient.WObj.setAlertHandler(new CollectingAlertHandler(collectedAlerts));

The problem I am having is that I getting this error in my Weclient Object –
 
webClient.AlertHandler' threw an exception of type 'System.InvalidOperationException
{"Operation is not valid due to the current state of the object."}
 
What am I missing.

Sam

**Comment by asbjornu** [comment]
I don't think you're missing anything. The NHtmlUnit library isn't really intended to support advanced use cases like these. Perhaps [HtmlUnit](http://htmlunit.sourceforge.net/) itself supports them better, but if you want advanced browser like functionality, I'd recommend [PhantomJS](http://phantomjs.org/) instead.

**Comment by asbjornu** [comment]
@samuelnyamukapa I think I've fixed the problem. I'll include it in the next release of NHtmlUnit.
