### ISSUE TITLE
Method not found: 'Void java.util.HashMap.__<clinit>()'.

### ISSUE THREAD

**Issue by enderteszla** [HtmlUnit/NHtmlUnit#21]
> System.MissingMethodException was unhandled by user code
>   HResult=-2146233069
>   Message=Method not found: 'Void java.util.HashMap.__<clinit>()'.
>   Source=HtmlUnit
>   StackTrace:
>        at com.gargoylesoftware.htmlunit.Cache..ctor()
>        at com.gargoylesoftware.htmlunit.WebClient..ctor(BrowserVersion browserVersion)
>        at NHtmlUnit.WebClient..ctor(BrowserVersion browserVersion)
>        at [our_project].FWWebClient.ClientWrapper..ctor(BrowserVersion version) in [our_project]\FWWebClient\ClientWrapper.cs:line 14
>        at [our_project].FWWebClient.WebClientPool..ctor() in [our_project]\FWWebClient\WebClientPool.cs:line 16
>        at [our_project]...
>   InnerException:

This error occurs after **IKVM.NET** update from **7.4.5196** to at least **8.0.5449** (the next one).
Using this version of **IKVM.NET** is critical for us because otherwise NHtmlUnit doesn' work with HTTPS in some cases due to _'Could not generate DH keypair' error at com.gargoylesoftware.htmlunit.WebClient.download(WebWindow requestingWindow, String target, WebRequest request, Boolean isHashJump, String description)_. As far as we can see, this is due to an obsolete Java version, that is, **IKVM.NET 7.4.5196** is too old. (Indeed, **IKVM.NET 8.0.5449** is more than a year old).
Could you please include the **IKVM 8.0.5449** support?

Thanks in advance,
Regards, L.B.

**Comment by asbjornu** [comment]
@enderteszla Thanks for your patience! I'm working on this in #25. When it and #23 is completed, I'll push out a new package on NuGet. I'll let you know here as soon as it's done.

**Comment by SkyGrain** [comment]
Excuse me whether has been solved? IKVM 8.1.5717.0 version, there is the problem. What should I do with?

**Comment by asbjornu** [comment]
@SkyGrain: I'm sorry, but #23 is still not complete, which is what I need to do before we can get a new release out the door. That release will hopefully fix the problem.

**Comment by asbjornu** [comment]
[NHtmlUnit 2.19.0](https://www.nuget.org/packages/NHtmlUnit/2.19.0) was released November 24th 2016 and should fix this. If not, please reopen.
