### ISSUE TITLE
[NHtmlUnit] - HtmlTextArea.SetText() not exist

### ISSUE THREAD

**Issue by tienducitt** [HtmlUnit/NHtmlUnit#22]
In java, HtmlTextArea.SetText() will set content of textarea. But in .NET, there are no SetText() method in HtmlTextArea.
I am using NHtmlUnit 2.15, how can I set content of textarea?
Do I miss something?

Thanks,

**Comment by tienducitt** [comment]
I have find out the way to that in C#.

 `htmlTextArea.Text = "new value";`

**Comment by BeeWarloc** [comment]
Yup.
That'ss basically what NHtmlUnit does with most setX/getX pairs, encapsulate them in a property.
