### ISSUE TITLE
Set up build on Travis

### ISSUE THREAD

**Issue by asbjornu** [HtmlUnit/NHtmlUnit#24]
To have a publicly available build on Linux, we should set up a build on [Travis](https://travis-ci.org/). I would do this myself if I could, but only an administrator of @HtmlUnit are allowed to create builds, so we need help from @asashour or someone else with the rights to do it.

**Comment by asashour** [comment]
Hi,
travis already has access to HtmlUnit
Please specify the steps needed.

I may be away for few days from tonight.
Thanks,Ahmed

**Comment by asbjornu** [comment]
@asashour [Seems like NHtmlUnit is already set up to run on Travis too](https://travis-ci.org/HtmlUnit/NHtmlUnit/settings). Awesome, thanks! :smile:

**Comment by asashour** [comment]
Clicked

**Comment by asbjornu** [comment]
@asashour Thanks!
