### ISSUE TITLE
[NHtmlUnit] - Too slow when enable javascript

### ISSUE THREAD

**Issue by tienducitt** [HtmlUnit/NHtmlUnit#26]
With the same browser setting, HtmlUnit took 8 seconds to navigate, but with NHtmlUnit it took 220 seconds,
Any ideas? Am i wrong somewhere?

Here is my setting:

``` c#
webClient = new WebClient(BrowserVersion.CHROME);
webClient.Options.JavaScriptEnabled = true;
webClient.Options.CssEnabled = false;
webClient.Options.AppletEnabled = false;
webClient.Options.Timeout = 30000;
webClient.Options.RedirectEnabled = true;
webClient.Options.ThrowExceptionOnFailingStatusCode = false;
webClient.Options.ThrowExceptionOnScriptError = false;
```

Navigate 

``` c#
page = WebBrowserHelper.Instance.navigate("http://vnraovat.net/register");
```

Thanks,

**Comment by asbjornu** [comment]
@tienducitt I expect that the overhead introduced by IKVM might be to blame, so there's not much we can do about this than hope performance get better with newer versions of IKVM. But how long does it take with JavaScript disabled? And what's the `WebBrowserHelper` class?

**Comment by tienducitt** [comment]
It 's work fine without javascript. 1 second with HtmlUnit and 3 second with NHtmlUnit.
`WebBrowserHelper` is just a small util, it does not effect performance.

So may be I have to find another solution in .NET, in java, it's work very nice.
Thank you,

**Comment by asbjornu** [comment]
@tienducitt That's ok. I'm trying to get out a new release based on the latest HtmlUnit and IKVM soon. I'll post here once it's out so you can re-run your test and see if it has improved. Sounds good?

**Comment by tienducitt** [comment]
My task is a litle bit urgent, so maybe now I need to find another solution to work in .NET.
Btw, thank you so much, create a new release and it will help someone like me in the future (include me).
Thank you and sorry for my english :))

**Comment by asbjornu** [comment]
I wouldn't expect this project to receive an update before IKVM is ported to .NET Core. See #35 for details.
