### ISSUE TITLE
Get Submit button without id ?

### ISSUE THREAD

**Issue by rullymartanto** [HtmlUnit/NHtmlUnit#31]
I have read the code but can't find out how to submit
How to submit form with input type submit ?
I am use C# 

Thanks

**Comment by asbjornu** [comment]
Hi. NHtmlUnit is just a C# wrapper around HtmlUnit, written in Java. Please refer to the [HtmlUnit documentation](http://htmlunit.sourceforge.net/gettingStarted.html) for how you use it.
