### ISSUE TITLE
GetFirstByXPath returns non wrapped com.gargoylesoftware.htmlunit... class

### ISSUE THREAD

**Issue by divaykin** [HtmlUnit/NHtmlUnit#7]
`homePage.GetFirstByXPath("//span[text()='Clinical']/parent::a")` returns non wrapped `HtmlAnchor`

**Comment by asbjornu** [comment]
That's because in HtmlUnit, `getFirstByXPath()` returns `object`, which currently isn't wrapped in NHtmlUnit. We could do runtime reflection of the returned type and wrap it, but that would introduce a bit overhead, plus I'm not quite sure how to do it.

**Comment by asbjornu** [comment]
@divaykin This should be fixed now. I decided to just wrap all returned `object` types.
