### ISSUE TITLE
Azure: Address family not supported by protocol family: connect

### ISSUE THREAD

**Issue by JitinDhillon** [HtmlUnit/NHtmlUnit#9]
Hi,

I'm trying to get NHtmlUnit working to do some basic web scraping on a website. It works fine on the local end, but when deployed onto a server (Windows Azure) I get the following error

'Address family not supported by protocol family: connect'

when it tries to execute .getPage on a WebClient.

Any idea why?

Greatly appreciate any help, thanks.

**Comment by gustavkn** [comment]
Fantastic, I've been looking for a solution for this problem for the last two months. Thanks!
